defaults:
  - _self_
  - data: ???
  - model: ???

# Model artifacts
artifacts:
  dir: artifacts
  model_file: ${data.name}_${model.name}_model.pkl
  features_file: ${data.name}_${model.name}_features.pkl

experiment:
  n_experiments: 100
  attack_attr: V4
  attack_val: 1
  new_val: 2
  frac: 0.1
  results_dir: results_${data.name}_${model.name}.csv
